### ISSUE TITLE
Updated code and automatic seasonal / x13as deployment

### ISSUE THREAD

**Issue by eddelbuettel** [NYTimes/gun-sales#1]
@gka, @joshkatz :  Congrats on the "gun sales" piece, and the fact that you documented code and data. That's how it should be done.

I had worked a litte with x-12 in the past, and also made some R package deployment more automatic w.r.t some external dependencies -- so I suggested to @christophsax to do something similar for his very nice [seasonal](https://github.com/christophsax/seasonal) package.  And so we did over the last few days.  

This now works and "should be on CRAN soon". In the meantime I have put packages for [x13binary](https://github.com/x13org/x13binary) and the  [development branch of seasonal](https://github.com/christophsax/seasonal/tree/x13download) into this [drat repo](http://ghrr.github.io/drat/) so that you can just install [seasonal](https://github.com/christophsax/seasonal) from it via `install.packages()` -- it will now pull in [x13binary](https://github.com/x13org/x13binary) which in turn will pull in working `x13ashtml` binaries on Windows, OS X, and Linux. The packages I uploaded are in source form (as I work on Linux) so you may need to add `type="source" but I could add Windows binaries if that helped you.

So the main thing is that we can now make the gun sales analysis truly automatic and failsafe. x13 will work.  I intend to make a few more local changes to your code.  I have a preference for also keeping project code in packages -- no disrespect to your [needs](https://github.com/joshkatz/needs) package now on CRAN -- so I may just tie this up some more.  E.g. the input data sets would then also be part of the package and be found no matter where the starting directory is.  All other dependencies are in fact on CRAN so we can really tie this up.

Which leads to my main question; Are you interested in a pull request for that, or would you rather leave this repo as it is?  I'd be perfectly happy to push my 'riff' on your work to, say, a repo 'gun-sales-package'.

Cheers,  Dirk

**Comment by gka** [comment]
Sure, that sounds awesome!

Super cool that x13 binaries are now included, so other people don’t have to compile the FORTRAN source code :)

Happy to accept your pull req for making our gun sales analysis a proper R package itself.

Cheers,
Gregor

On January 2, 2016 at 11:44:26 AM, Dirk Eddelbuettel (notifications@github.com) wrote:

@gka, @joshkatz : Congrats on the "gun sales" piece, and the fact that you documented code and data. That's how it should be done.

I had worked a litte with x-12 in the past, and also made some R package deployment more automatic w.r.t some external dependencies -- so I suggested to @christophsax to do something similar for his very nice seasonal package. And so we did over the last few days.

This now works and "should be on CRAN soon". In the meantime I have put packages for x13binary and the development branch of seasonal into this drat repo so that you can just install seasonal from it via install.packages() -- it will now pull in x13binary which in turn will pull in working x13ashtml binaries on Windows, OS X, and Linux. The packages I uploaded are in source form (as I work on Linux) so you may need to add `type="source" but I could add Windows binaries if that helped you.

So the main thing is that we can now make the gun sales analysis truly automatic and failsafe. x13 will work. I intend to make a few more local changes to your code. I have a preference for also keeping project code in packages -- no disrespect to your needs package now on CRAN -- so I may just tie this up some more. E.g. the input data sets would then also be part of the package and be found no matter where the starting directory is. All other dependencies are in fact on CRAN so we can really tie this up.

Which leads to my main question; Are you interested in a pull request for that, or would you rather leave this repo as it is? I'd be perfectly happy to push my 'riff' on your work to, say, a repo 'gun-sales-package'.

Cheers, Dirk

**Comment by eddelbuettel** [comment]
Awesomesauce -- will do.  

Still wondering whether I should wait til we have everything on CRAN or proceed now that we have the OSs that matter covered -- probably the latter.   I'll get back to you in a few days.  If you want to poke around, I already have it working in [a branch here](https://github.com/eddelbuettel/gun-sales/tree/feature/revised-code) which has updated `README.md` and `main.R` using the new functionality.   

But this change set is more invasive as I really don't like `%>%` so I rewrote use of that in a few places too -- I won't make that change in a pull request which will focus on the more important 'bigger picture' issue: package creation, Depends, and automated installation of the x-13arima-seats binary.

**Comment by eddelbuettel** [comment]
Hi @gka and @joshkeller -- I now have a working package which passes `R CMD check --as-cran` cleanly.  One main function `analysis()` with help page, automatically loaded data sets with help, ...
It is all in this [this branch](https://github.com/eddelbuettel/gun-sales/tree/feature/revised-code). 

You will need updated / development versions of [seasonal](https://github.com/christophsax/seasonal) and [x13binary](https://github.com/x13org/x13binary). Give @christophsax and myself a few days to square some issues up and then we should be ready.

**Comment by eddelbuettel** [comment]
Quick update:  the package is now on [CRAN as x13binary](http://cloud.r-project.org/package=x13binary) which should have Windows binaries by tomorrow, and OS X binaries in a few days too.

**Comment by eddelbuettel** [comment]
@gka:  When you get a chance, let me know if the following now works:

``` r
install.packages("seasonal")       # maybe with type="source";  should pull in x13binary
library(gunsales)
analysis()         # all plots via base graphics
gganalysis()       # all plots via ggplot2
```

**Comment by gka** [comment]
Installing seasonal seems to work.

But shouldn't there be an `install.packages("gunsales")` somewhere? Still get the same error 

``` R
> analysis()
Error in UseMethod("mutate_") : 
  no applicable method for 'mutate_' applied to an object of class "function"
```

Tried to re-install `gunsales` from source, but that failed.

``` bash
$ git clone git clone git@github.com:NYTimes/gun-sales.git
$ cd gun-sales
$ R CMD INSTALL . 
* installing to library ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library’
ERROR: dependencies ‘data.table’, ‘zoo’ are not available for package ‘gunsales’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/gunsales’
```

**Comment by eddelbuettel** [comment]
Yes. That is because `gunsales` is so far just a repo.  So what I do is roughly 

``` bash
cd ~/git/gun-sales
git pull --all
cd ..
R CMD build gun-sales                 # need to build to prepare for vignettes
R CMD INSTALL gunsales_0.1.0.tar.gz   # actually install gunsales packages
```

after which you can do

``` r
library(gunsales)
analysis()         # all plots via base graphics
gganalysis()       # all plots via ggplot2
```

which should "just work".  Sorry for not making that clearer.

**Comment by gka** [comment]
```
$ R CMD build gun-sales
* checking for file ‘gun-sales/DESCRIPTION’ ... OK
* preparing ‘gunsales’:
* checking DESCRIPTION meta-information ... OK
Error in loadVignetteBuilder(pkgdir, TRUE) : 
  vignette builder 'knitr' not found
Execution halted
```

Do I need to setup some paths in `~/.Renviron` maybe?

http://stackoverflow.com/a/26814422

**Comment by eddelbuettel** [comment]
I think I had that once on Windows too.  Package building there (and seemingly on OS X) appears to happen in a limited / reduced environment.  Linux doesn't have that issue.

The R_LIBS_USER via `~/.Renviron` idea is fine; you could also as a last resort install knitr (and whatever else is needed) in your code R library path.

On Linux I can just do 'library(knitr)' and it is being found. In normal sessions, and when building packages.

**Comment by gka** [comment]
``` r
> needs(knitr, zoo, data.table)
```

solved the install problems

**Comment by eddelbuettel** [comment]
No, not `needs()` as (approximately) nobody outside of the NY Times building has that. Use

``` r
install.packages(c("knitr", "zoo", "data.table"))
```
