### ISSUE TITLE
examples failing on CRAN oldrel and Solaris

### ISSUE THREAD

**Issue by christophsax** [NYTimes/gun-sales#14]
Sorry, only realized it now that you may have this problem on CRAN: The examples will cause ERRORs on the Win oldrel and Solaris platform, as X-13 is (currently) not working there. The [ggseas](https://cran.r-project.org/web/packages/ggseas/index.html) package had the same problem.

```
#' @examples
#' gs <- analysis()
#' plot_gunsales(gs)
#' ggplot_gunsales(gs)
```

For seasonal, I put all the examples inside `\dontrun{}`, e.g. [here](https://github.com/christophsax/seasonal/blob/master/man/seas.Rd).

To actually run tests on the CRAN machines, I put them inside this condition:

```
r.version <- paste(R.Version()$major, R.Version()$minor, sep = ".")
is.oldrel <- .Platform$OS.type == "windows" && (compareVersion(r.version, "3.1.3") < 1)
if (x13binary::supportedPlatform() && !is.oldrel){
}
```

See [here](https://github.com/christophsax/seasonal/blob/master/tests/cran-tests.R).

The oldrel issue is hopefully temporary and will be resolved with a new R Version. Later on, we could also wrap the examples in:

```
if (x13binary::supportedPlatform(){
}
```

**Comment by eddelbuettel** [comment]
Ugggh. Should have checked with you.  I guess we'll update in a bit.

**Comment by eddelbuettel** [comment]
I actually put two of the three examples into `\dontrun{}` as Uwe was complaining about timing. Either make that that 3 out of 3, or condition more finely as you suggest here.

**Comment by eddelbuettel** [comment]
So to recap I can
- if we had a `tests/` directory, I would condition there; as we do not I do not have to -- but as a result of this I may end up writing a `tests/simpleTest.R`
- the remaining example will get a `\dontrun{}`. I don't quite like that but _c'est la vie_.
- the vignette is a nut I need to crack.  Maybe I just have to turn it into static display then rather than actually re-running. Need to think about that.
